### ISSUE TITLE
[Security] Workflow ci.yml is using vulnerable action py-actions/py-dependency-install

### ISSUE THREAD

**Issue by Ale0x78** [fafhrd91/aiohttp#6444]
The workflow ci.yml is referencing action py-actions/py-dependency-install using references v2. However this reference is missing the commit [5df6847b1bc7e7eff410a6d05aab1708d592de20](https://github.com/py-actions/py-dependency-install/commits/5df6847b1bc7e7eff410a6d05aab1708d592de20) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by Dreamsorcerer** [comment]
@Ale0x78 If this is an NCSU project being worked on or something, please stop spamming everyone with useless messages. Test your project against a handful of repos, rather than 100s of them, and don't have every student repeat the same thing on public repositories (use a dry-run or something which doesn't actually post an issue).
