### ISSUE TITLE
EofStream and websocket.receive_* functions

### ISSUE THREAD

**Issue by socketpair** [fafhrd91/aiohttp#6800]
aiohttp 3.8.1

`await websocket.receive_json()` Will die with `TypeError` on `WSMsgType.CLOSED`.

#2784 is fixed, yes:

```python
 async def __anext__(self) -> WSMessage:
        msg = await self.receive()
        if msg.type in (WSMsgType.CLOSE, WSMsgType.CLOSING, WSMsgType.CLOSED):
            raise StopAsyncIteration
        return msg
```

Yes, bug is fixed in iterator but NOT fixed for `websocket.receive_*` functions, like `receive_json()`

I would raise RuntimeError or so if corresponding message "type" (like bytes, str, or json) can not be received.

**Comment by rigtorp** [comment]
First I want to thank the developers for this amazing library!

I have the same issue. The `webscocket.receeive_*` functions should throw `ConnectionResetError` when there are connection related errors instead of `TypeError`.  It will already throw this error if the auto ping feature is enabled and the `pong`  call fails.

**Comment by ara-25** [comment]
Hi,
If this issue still persists and is available, then I would like to take it up for the hacktoberfest event.

**Comment by Dreamsorcerer** [comment]
Yep, go ahead. I think you'll find those functions in aiotttp/client_ws.py.
