### ISSUE TITLE
Host header position is locked

### ISSUE THREAD

**Issue by redacted-text** [fafhrd91/aiohttp#6904]
### Describe the bug

Why did you implemented #3265?
Now I need to move this header position, and you locked it.

### To Reproduce

-

### Expected behavior

-

### Logs/tracebacks

```python-traceback
-
```

### Python Version

```console
any
```

### aiohttp Version

```console
-
```

### multidict Version

```console
-
```

### yarl Version

```console
-
```

### OS

-

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
> Why did you implemented #3265?

I think it's quite clearly explained in that issue.

There's probably no way we can please everyone with a dodgy, non-conformant server.

In fact, the change in that issue is directly conformant with the HTTP protocol:
> Since the Host field-value is critical information for handling a request, a user agent SHOULD generate Host as the first header field following the request-line.
https://httpwg.org/specs/rfc7230.html#header.host

So, we are doing the correct thing here. Not sure what strange server you need to move the Host header for, but it's going to be awkward anyway (given that browsers, and most other clients would send the Host first).

**Comment by Dreamsorcerer** [comment]
As this is a very unusual requirement, that almost nobody should need, we probably won't accept any changes for this behaviour.

Therefore, I'd suggest just monkey patching `ClientSession.update_headers()` to make the behaviour the way you need for your unique case.
