### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by celestinoxp** [fafhrd91/aiohttp#7162]
### Describe the bug

please update charset-normalizer dependecy

### To Reproduce

.

### Expected behavior

charset-normalizer 3.0.1

### Logs/tracebacks

```python-traceback
.
```

### Python Version

```console
$ python --version

Python 3.9.13
```

### aiohttp Version

```console
$ python -m pip show aiohttp

Name: aiohttp
Version: 3.8.3
```

### multidict Version

```console
$ python -m pip show multidict

Name: multidict
Version: 6.0.4
```

### yarl Version

```console
$ python -m pip show yarl

Name: yarl
Version: 1.8.2
```

### OS

Windows 11 x64

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
You means raise the upper bounds?

We already have: https://github.com/aio-libs/aiohttp/blob/master/setup.cfg#L50

Will be in the next release.

**Comment by celestinoxp** [comment]
> Will be in the next release.

when will the next release be?

**Comment by webknjaz** [comment]
Dunno. Honestly, it'd be nice to improve Python 3.11 stability before planning the new release.

**Comment by MarcoGlauser** [comment]
Poetry doesn't upgrade our aiohttp package past 3.7.4.post0 because of the charset-normalizer dependency boundaries. 
We only have it as a transitive dependency from black and it's causing issues upgrading to python 3.11. 
(Same issue from someone else in the poetry repo https://github.com/python-poetry/poetry/issues/7360)
