### ISSUE TITLE
`certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]`. The `requests` library works fine though.

### ISSUE THREAD

**Issue by fatboychummy** [fafhrd91/aiohttp#7287]
### Describe the bug

I am getting an SSL error when attempting to connect to multiple hosts. `discord.com` here being the main one, as I'm writing a bot with `discord.py`.

Now, I've narrowed it down to be an issue with this module, as the `requests` module *does* successfully connect to discord.

The minimal code that I have is the following:
```python
import asyncio
import aiohttp

async def main():
  async with aiohttp.ClientSession() as session:
    async with session.get('https://discord.com') as response:
      print('Status: ', response.status)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

The above code *does not* work when ran, and produces the sslerror.

The below code *does* work, and returns a 200 status on command line.
```python
import requests
requests.get("https://discord.com", verify=True)
```

### To Reproduce

I am unsure what exactly is causing the issue on my end. I'll be happy to provide as much detail as possible though, I just don't know what is needed.

### Expected behavior

A valid connection to discord.

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "/home/fatbot/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.9/asyncio/sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "<stdin>", line 3, in main
  File "/home/fatbot/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/fatbot/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/fatbot/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/fatbot/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/fatbot/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/home/fatbot/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/fatbot/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]
```

### Python Version

```console
$ python --version
Python 3.9.5
```

### aiohttp Version

```console
$ python -m pip show aiohttp
<... clipped ...>
Version: 3.8.4
<... clipped ...>
```

### multidict Version

```console
$ python -m pip show multidict
<... clipped ...>
Version: 6.0.4
<... clipped ...>
```

### yarl Version

```console
$ python -m pip show yarl
<... clipped ...>
Version: 1.9.2
<... clipped ...>
```

### OS

Ubuntu Server 20.04

### Related component

Client

### Additional context

Running on a Contabo VPS,

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Search "certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)".

Your Python install is probably missing certificates or something. There is a command somewhere that can be used to install them.

Normally, on something like Ubuntu, this would be already done, so no idea what's happened to your setup.

My only guess about requests working is that it may have installed and used another package (like certifi) to get this working without having it working in core python.

**Comment by fatboychummy** [comment]
> Search "certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)".

I have -- I've been trying to resolve this for about three and a half days now. Every issue I've found is either about Windows, Mac, or just outright hasn't worked.

Is there a different certificate store that `aiohttp` uses or something? Where should I be looking for the cert files for aiohttp, or does it use the standard `/etc/ssl/certs` folder?

Edit to add: `certifi.where()` points to this same folder as well, so certifi is using the ubuntu standard at least.

**Comment by Dreamsorcerer** [comment]
I'm pretty sure we don't do anything with certificates directly, it all comes from Python.
So, probably either handled in the transport (https://docs.python.org/3/library/asyncio-protocol.html#transports) or the SSL context (https://docs.python.org/3/library/ssl.html#ssl.SSLContext).

Maybe another reason it could work with requests but not aiohttp is some bug in the asyncio implementation, but I've not seen this before...

Worst case, you can always try loading an explicit certificate chain in a SSLContext and then pass that into the ClientSession.

**Comment by Dreamsorcerer** [comment]
This one might be particularly relevant:
https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_verify_locations

**Comment by johnfung95** [comment]
Hi, may I know if this issue is resolved? 
Because I am having the same problem. It works with the requests library, where I submitted my client cert with `requests.get(url, cert='cert.pem')`, it works just fine. However, when I switched to aiohttp library, it seems like I am not getting anywhere. 

Here is my code for reference:
`context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
context.load_verify_locations(cafile='path/to/ca.pem')
ssl_conn = aiohttp.TCPConnector(ssl_context=context)
  async with aiohttp.ClientSession(connector=ssl_conn) as session:
    response = await session.get(url)
    return response.text()
`

I have no idea where I did wrong and I have been struggling for quite some days now. I have to pass in my client certificate to make a request, so skipping the verification with `ssl=False` is not an option.

Here is my log traceback for reference:
`Traceback (most recent call last):
  File "C:\Users\TD\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TD\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1106, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TD\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1139, in _create_connection_transport
    await waiter
  File "C:\Users\TD\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 574, in _on_handshake_complete
    raise handshake_exc
  File "C:\Users\TD\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 556, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\TD\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)`

**Comment by Dreamsorcerer** [comment]
Your requests example adds a client-side certificate.
Your SSLContext example loads a CA certificate (i.e. something to validate the server's certificate with).
For client-side certificate, you want https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_cert_chain

To ensure you have a reasonable SSLContext created with the default CA certs, you'll probably also want to get a SSLContext with https://docs.python.org/3/library/ssl.html#ssl.create_default_context instead of instantiating one directly.

**Comment by johnfung95** [comment]
@Dreamsorcerer oic, my bad. After using the `load_cert_chain`, I can successfully send my request with the client certificate. Thank you very much!

**Comment by fatboychummy** [comment]
For those wondering what happened to this -- I just gave up and full reinstalled my Linux system (though honestly that was something I've been needing to do for a while anyways).

It works now, so it must have been some obscure configuration issue on my end.
