### ISSUE TITLE
HTTPS requests received on HTTP port show generic BadStatusLine exception

### ISSUE THREAD

**Issue by codyc1515** [fafhrd91/aiohttp#8065]
### Describe the bug

When an HTTPS request is sent to the HTTP server port, a generic exception is thrown `aiohttp.http_exceptions.BadStatusLine: 400, message: Invalid method encountered`.

This has caused confusion for some Home Assistant users with a misconfigured reverse-proxy set-up. With this message, it is not always clear where the issue is. [Example](https://github.com/home-assistant/core/issues/108533).

### To Reproduce

Send a HTTPS request on the HTTP port.

### Expected behavior

b'\x16\x03' appears to be a known HTTPS connection message. Given that we know this, a more descriptive error message (in lieu of `Invalid method encountered`) could be provided, such as `Received HTTPS traffic on HTTP port`.

### Logs/tracebacks

```python-traceback
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 8:32:09 AM (12 occurrences)
Last logged: 8:32:10 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x03\x01F\x01'
      ^
```

### Python Version

```console
3.11.6
```

### aiohttp Version

```console
3.9.1
```

### multidict Version

```console
6.0.4
```

### yarl Version

```console
1.9.4
```

### OS

Home Assistant OS 11.4

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by andersk** [comment]
This is becoming more frequent due to Chromium’s [automatic HTTPS upgrades](https://chromestatus.com/feature/6056181032812544), where HTTPS requests are attempted on the same port if a port number is specified in the URL.

- https://github.com/whatwg/fetch/pull/1655#issuecomment-1938971347

**Comment by Dreamsorcerer** [comment]
Seems reasonable if someone want to volunteer to make the change. It will need a change for both Python and Cython parsers.

**Comment by bdraco** [comment]
This error comes up quite often when there isn't anything actually wrong.  We should probably downgrade it to debug logging.

https://github.com/aio-libs/aiohttp/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+BadStatusLine

**Comment by bdraco** [comment]
Looks like this comes up fairly frequently downstream as well
https://github.com/home-assistant/core/issues/130851
https://github.com/home-assistant/core/issues/130460
https://github.com/home-assistant/core/issues/124653
https://github.com/home-assistant/core/issues/128266
https://github.com/home-assistant/core/issues/73885

**Comment by Dreamsorcerer** [comment]
I think it makes sense to make it a debug log at this point, though the noisiness in the past has been pretty helpful as most exceptions reported turned out to be parser bugs. I'm a lot more confident in the parser these days, so don't mind reducing the output.

But, even logging, we should improve the error message in this specific case by checking the first 2 bytes are `\x16\x03` to make it easier to debug. Surely all those homeassistant issues will be more difficult for users to debug with the linked PR? i.e. They are now less likely to see the errors and those errors still don't explain the issue with their client clearly. I think HTTPS on HTTP port is such a common case that we can special case it. @bdraco Maybe something even simpler than #10067 and just change the error message (rather than the exception class)?
