### ISSUE TITLE
Documentation mentions async_timeout as dependency

### ISSUE THREAD

**Issue by mdczaplicki** [fafhrd91/aiohttp#8379]
### Describe the bug

The documentation mentions that `async_timeout` is one of the dependencies of `aiohttp`, but it's not.

https://docs.aiohttp.org/en/stable/#dependencies

### To Reproduce

1. Install `aiohttp==3.9.5`
2. `import async_timeout`

### Expected behavior

Works

### Logs/tracebacks

```python-traceback
x
```

### Python Version

```console
$ python --version
3.11.9
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.9.5
```

### multidict Version

```console
$ python -m pip show multidict
```

### yarl Version

```console
$ python -m pip show yarl
```

### OS

x

### Related component

Client

### Code of Conduct

- [ ] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
It is a fallback in older runtimes: https://github.com/aio-libs/aiohttp/blob/4928ae3/setup.cfg#L54 / https://github.com/aio-libs/aiohttp/blob/4928ae3/aiohttp/client_ws.py#L28. The stdlib is always preferred when available.

This is not a software bug but a documentation issue. Anyway, you shouldn't be relying on transitive dependencies — it's wrong from the packaging perspective. If you use something directly from your code base, that's your direct dependency and you should treat it as such instead of hoping that something else will bring it in occasionally.

**Comment by mdczaplicki** [comment]
Of course I shouldn't be relying, but that's why I've found it 😁 I've already switched to native.  I've just thought that I'll let you know.
Thanks!
