### ISSUE TITLE
RuntimeError: no running event loop

### ISSUE THREAD

**Issue by tomplus** [fafhrd91/aiohttp#8555]
### Describe the bug

It looks like a breaking change in the latest version. 

In version 3.9.5 it works:

```
import aiohttp
connector = aiohttp.TCPConnector()
```

(in a more complex example I get a warning (DeprecationWarning: The object should be created within an async function))

but in 3.10 I get an exception:

```
Traceback (most recent call last):
  File "/tmp/a1.py", line 5, in <module>
    connector = aiohttp.TCPConnector()
  File "/home/tomek/work/github/kubernetes-client/kubernetes_asyncio-new/VENV/lib/python3.10/site-packages/aiohttp/connector.py", line 784, in __init__
    super().__init__(
  File "/home/tomek/work/github/kubernetes-client/kubernetes_asyncio-new/VENV/lib/python3.10/site-packages/aiohttp/connector.py", line 234, in __init__
    loop = loop or asyncio.get_running_loop()
RuntimeError: no running event loop
```

### To Reproduce

code
```
import aiohttp
connector = aiohttp.TCPConnector()
```

### Expected behavior

If the change is intentional it would be very useful to describe that in a changelog. 
If not I expect the same behavior like in the previous version.

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "/tmp/a1.py", line 5, in <module>
    connector = aiohttp.TCPConnector()
  File "/home/tomek/work/github/kubernetes-client/kubernetes_asyncio-new/VENV/lib/python3.10/site-packages/aiohttp/connector.py", line 784, in __init__
    super().__init__(
  File "/home/tomek/work/github/kubernetes-client/kubernetes_asyncio-new/VENV/lib/python3.10/site-packages/aiohttp/connector.py", line 234, in __init__
    loop = loop or asyncio.get_running_loop()
RuntimeError: no running event loop
```
```


### Python Version

```console
$ python --version
3.10
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.10.0
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.4
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.8.2
```

### OS

Linux

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by bdraco** [comment]
It looks like this is caused by #8512

**Comment by bdraco** [comment]
It looks like it was deprecated in 3.9.5 and now no longer works in 3.10.0 https://github.com/aio-libs/aiohttp/blob/3.9/aiohttp/helpers.py#L296 but https://github.com/aio-libs/aiohttp/pull/5278 didn't have a changelog message to say it would stop working.

In 3.9.5 it would create a new non-running event loop
```
>>> import aiohttp
>>> print(aiohttp.__version__)
3.9.5
>>> connector = aiohttp.TCPConnector()
>>> print(connector._loop)
<_UnixSelectorEventLoop running=False closed=False debug=False>
>>> 
```

**Comment by bdraco** [comment]
Based on the above, I'd say the change is intentional but could use a changelog entry.

**Comment by bdraco** [comment]
Creating a `Client`, `CookieJar`, or `Connector` without a running `asyncio` event loop will now explicitly raise in 3.10.0

**Comment by aslonnie** [comment]
is this going to be fixed in 3.10.1 ? or is this breakage intentional?

**Comment by bdraco** [comment]
As it was deprecated over 5 years ago, there is no plan to extend the deprecation period

**Comment by webknjaz** [comment]
https://hynek.me/articles/semver-will-not-save-you/#taking-responsibility

**Comment by TheDurableDane** [comment]
@webknjaz That's a bit passive-aggressive. I know I shouldn't blindly trust any package I use, but sematic versioning best pratices would be a nice touch for such a widely used package as aiohttp. I don't think you are excused just because you can link to a blog post that says it's the user's fault.

**Comment by bdraco** [comment]
I thought about reverting this change, but I'm not sold on that idea because because python itself has deprecated calling `asyncio.get_event_loop()` without a running event loop because the behavior is confusing.

https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop
<img width="826" alt="Screenshot 2024-08-01 at 2 27 12 PM" src="https://github.com/user-attachments/assets/7e615dea-8227-46c2-88a3-772e36b6587a">

**Comment by webknjaz** [comment]
@TheDurableDane you're right the end-users should be able to rely on the documented expectations. Could you point out where we promise that the first version component alone corresponds to SemVer's major version? My observation is that major has always two components.
Besides, SemVer is talking about public APIs and my understanding is that those haven't changed.
And finally, people who make releases may interpret things differently, compared to those consuming them. I keep seeing this problem where the users invent something in their heads and think this always matches the mental models of others. That's not how it works. SemVer by its nature ultimately represents how the maintainers see changes, not necessarily how every single user perceive them.

**Comment by Dreamsorcerer** [comment]
Just to add to bdraco's conclusion, I think the old code may have been dangerously wrong in some situations.
If you create TCPConnector as a global, the get_event_loop() call would create a new loop and store the reference for later.
If you then run your application with asyncio.run() or web.run_app(), it will create a new loop to execute the application in.
You then have your application running in one loop and TCPConnector trying to do callbacks etc. in another loop which isn't even running.

**Comment by bdraco** [comment]
[0001-Restore-the-ability-to-create-objects-without-a-runn.patch](https://github.com/user-attachments/files/16470284/0001-Restore-the-ability-to-create-objects-without-a-runn.patch)

Attached is a patch for anyone who arrives at this issue in the future because a security 
issue requires them to update to 3.10.x or later and needs a quick solution until they
can adjust their object creation.

**Comment by kyrlon** [comment]
> [0001-Restore-the-ability-to-create-objects-without-a-runn.patch](https://github.com/user-attachments/files/16470284/0001-Restore-the-ability-to-create-objects-without-a-runn.patch)
> 
> Attached is a patch for anyone who arrives at this issue in the future because a security issue requires them to update to 3.10.x or later and needs a quick solution until they can adjust their object creation.

Can confirm this works on my Windows 10 machine:
```
OS: Windows 10
Python version: Python3.12
aiohttp==3.10.5
```
however got this working by manual alterations. 
1. I cannot for the life of me build from source (or pip install via `py -m pip install git+https://github.com/aio-libs/aiohttp.git`), so that was my first issue
2.  At the time of this post, I was using `aiohttp==3.10.5`, so when I did attempt to patch, it failed. Manual modifications was a slow and patient process (inspecting the patch with a text editor), but was able to do such an example on my current system from this [article](https://blog.jonlu.ca/posts/async-python-http):
```
import sys
import os
import json
import asyncio
import aiohttp


# Initialize connection pool
conn = aiohttp.TCPConnector(limit_per_host=100, limit=0, ttl_dns_cache=300)
PARALLEL_REQUESTS = 100
results = []
urls = ['https://jsonplaceholder.typicode.com/todos/1' for i in range(4000)] #array of urls

async def gather_with_concurrency(n):
    semaphore = asyncio.Semaphore(n)
    session = aiohttp.ClientSession(connector=conn)

    # heres the logic for the generator
    async def get(url):
        async with semaphore:
            async with session.get(url, ssl=False) as response:
                obj = json.loads(await response.read())
                results.append(obj)
    await asyncio.gather(*(get(url) for url in urls))
    await session.close()
if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(gather_with_concurrency(PARALLEL_REQUESTS))
    conn.close()

    print(f"Completed {len(urls)} requests with {len(results)} results")
```

**Comment by zeocax** [comment]
This may help

```python
import aiohttp
import asyncio

async def create_session():
    return aiohttp.ClientSession()

aiohttp_client_session = asyncio.get_event_loop().run_until_complete(create_session())
```

**Comment by Dreamsorcerer** [comment]
As mentioned above, very likely to break your application (now or in the future).
