### ISSUE TITLE
Rename compress parameter

### ISSUE THREAD

**Issue by Dreamsorcerer** [fafhrd91/aiohttp#8928]
The request() method has a compress parameter which forces compression even when the headers are not set, leading any normal server to not know the request is compressed.

This is a useless option for most people. If we can't remove the option, we should atleast rename it to something that stops people using it by mistake.

We've had many users report bugs due to this confusion.

**Comment by wfatherley** [comment]
Tracing the parameter starting at `ClientSession._request`, it's passed to `ClientRequest`:

https://github.com/aio-libs/aiohttp/blob/1d170d37f476df705a9dcc3588e192e8ccb871c0/aiohttp/client.py#L572


where it's stored as an attribute. It's then passed to the request object's writer here:

https://github.com/aio-libs/aiohttp/blob/1d170d37f476df705a9dcc3588e192e8ccb871c0/aiohttp/client_reqrep.py#L639


Seems that this if-block might be the last point at which the parameter can be interpolated into a Content Encoding header. Because `ClientSession` and the corresponding objects it interacts with support other parameters that are essentially header values, it doesn't feel unreasonable to keep it around so long as it's not a headache for users. One thing that is worth discussing before implementing a fix is would the value of the parameter `compress` have precedence over a Content Encoding header if both were passed in?

**Comment by Dreamsorcerer** [comment]
Hmm, maybe I misread it...
It does set a header at:
https://github.com/aio-libs/aiohttp/blob/1d170d37f476df705a9dcc3588e192e8ccb871c0/aiohttp/client_reqrep.py#L438-L441

Any chance you could create an xfail test based on one of the bug reports?
See for example: #3413

**Comment by wfatherley** [comment]
So there’s no worry on the edge case of setting the compress attribute after the call to `__init__`? I was going to suggest that the header-bound parameters reside in descriptor-based attributes, which could circumvent the ceremonial `update_*` methods…

I’ll have a look at that issue and see what I can come up with :)

**Comment by Dreamsorcerer** [comment]
> So there’s no worry on the edge case of setting the compress attribute after the call to `__init__`?

Hadn't really thought about that. Not sure why anyone would change it via attribute. But, if that's a problem, we can easily just use `@property` to call that method when it's changed (or just make it read-only in future).

**Comment by Dreamsorcerer** [comment]
Might already be a test in #5478.

**Comment by Dreamsorcerer** [comment]
Nevermind, that test is nonsense. The behaviour in that test works as expected.

**Comment by Dreamsorcerer** [comment]
Actually, if the test is corrected to use the correct method, then it seems to reproduce the problem when using the C parser. But, works fine with the Python parser...
